# Datasource H2 em modo ficheiro (persiste entre reinícios)
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:./data/simulacoes;DB_CLOSE_DELAY=-1
quarkus.datasource.username=sa
quarkus.datasource.password=

# Hibernate - gera as tabelas automaticamente (drop-and-create para protótipo)
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

# OpenAPI - define título e versão
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=always
mp.openapi.extensions.smallrye.info.title=API de Simulação de Financiamentos
mp.openapi.extensions.smallrye.info.version=1.0.0

